import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

type Props = {
  ip: string;
};

const Home = (props: Props) => {
  const { ip } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS - IP Address getStaticProps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>IP Adress with getStaticProps</h1>

        <p className={styles.description}>
          Your IP is: <code className={styles.code}>{`${ip}`}</code>
        </p>
      </main>
    </div>
  );
};

export default Home;

Home.getInitialProps = async (ctx: NextPageContext) => {
  const ip = ctx?.req?.headers["x-real-ip"] || ctx?.req?.socket.remoteAddress;

  return {
    props: {
      ip,
    },
  };
};
