import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

const ServerIP: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS - IP Address getStaticProps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          IP Adress with getServerSideProps and Middleware
        </h1>

        <p className={styles.description}>Show your network tab in Devtools</p>
      </main>
    </div>
  );
};

export default ServerIP;
